# Generated by Django 5.2.8 on 2025-11-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pro_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=50)),
                ('pro_description', models.CharField(max_length=200)),
                ('pro_cat_image', models.ImageField(upload_to='category_image')),
            ],
        ),
    ]
